### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by vijay-vanecha** [Treri/angular-ios-alertview#3]
Hi, Awesome plugin!

One suggestion for confirmation popup option. If it is bottom aligned to screen with save & discard buttons. Like as below image.

![ios_popup_bottom](https://cloud.githubusercontent.com/assets/2329736/13070152/1f0f58da-d4b0-11e5-9d36-a07592aabea6.png)

Thanks

**Comment by ik0r** [comment]
@vijay-vanecha  Maybe you can try my another plugin [angular-ios-actionsheet](https://github.com/Treri/angular-ios-actionsheet)

**Comment by vijay-vanecha** [comment]
You are just awesome!

Thanks again. :)
