### ISSUE TITLE
Is there any possibility in prompt option have two input fields?

### ISSUE THREAD

**Issue by vijay-vanecha** [Treri/angular-ios-alertview#4]
Hi,

Is there any possibility in prompt option have two input fields?

Thanks again.

**Comment by ik0r** [comment]
Two input fields?

This plugin now not support that. But PRs are welcome

**Comment by vijay-vanecha** [comment]
Thanks for reply,

I also think if it support custom HTML template in alertview then it will awesome.

Thanks again.

**Comment by ik0r** [comment]
@vijay-vanecha yes. html is supported. you can find $sce usage in source code

**Comment by vijay-vanecha** [comment]
I will check and try that.

Thanks for your support.
